### ISSUE TITLE
Gene names in pathway thumbnails

### ISSUE THREAD

**Issue by hattrill** [FlyBase/GO-curation#69]
Check and update pathway thumbnails for updated gene symbols:

e.g. 
Akt1 -> Akt (PVR, Insulin)
This is fine as Nick asked for change when making thumbnail

But need to check over others...

**Comment by gantonazzo** [comment]
While checking, I saw the following:

- [x] Activin seems fine

- [x]  BMP seems fine

- [x]  For cGAS-STING we have "cGLR1" and "cGLR2", while the symbols in FB are "cGlr1" and "cGlr2". Also, Relish is represented as "rel", but the symbol in FB is "Rel"

- [x]  For EGFR in the thumbnail there is "cbl", but the symbol is "Cbl"

- [x]  FGFR seems fine

- [x]  In the Hedgehog thumbnail there is a minimal issue: "CkIα" is represented as "Ck1α", so using Arabic numbers instead of Roman. Then "slmb" is shown as "Slmb". Cul1 and Roc1a had to be solid shapes

- [x]  In Hippo "ft" is shown as "fat"; "shg" is in the thumbnail, but not in the group; "Zyx" is shown as "zyx"; there is a lonely "d", which I suppose should be "dachs"?

- [x]  Imd: "Uev1A" is shown as "Uev1a"; Shouldn't "Tab1" in the thumbnail be "Tab2"?; "Rel" is again shown as "rel"; NOTE: "Jra" is not in the pathway group

- [x]  Insulin: this is minor, but "PI3K" could be "Pi3K"; "Tor" has now become "mTor", and Lst8 had to be removed from TORC1

- [x]  JAK-STAT Cul2 needed to be Cul2,5

- [x]  Notch: "Dl" is now "Delta"; NOTE: "gro" and "CtBP" are not in the group

- [x]  Pvr: "Tor" in now "mTor"; "PI3K" could be "Pi3K"; NOTE: "raptor" is not in the group

- [x]  Sevenless: "sos" in thumbnail should be "Sos"

- [x]  TNFalpha/Eiger: "Uev1A" is shown as "Uev1a"

- [x]  Toll seems fine

- [x]  Torso seems fine

- [x]  Wnt-TCF: "Slmb" in thumbnail should be "slmb"

**Comment by hattrill** [comment]
Hey @gantonazzo we have a budget for an annual subscription to Adobe Creative Cloud - do you want to get this and then we can edit when we like rather than having to go via Nick?

**Comment by gantonazzo** [comment]
I guess we could do it, so we can edit the gene names ourselves. Previously these kind of licenses were bought by Steven with a PO. How does it work now?

**Comment by sjm41** [comment]
I just renewed Nick's license.  You need to buy it via the Academia PunchOut on the CUFS system, and register it to a particular user. Can either get all products (creative cloud) or just specific products (e.g. illustrator), which is cheaper.  I can do it for you if u like.

**Comment by hattrill** [comment]
We budgeted for creative cloud, so shall we both get licences for that Giulia? Be good for designing logos ;-)

If we don't get much use from them, then we can scale back to illustrator next year.

**Comment by gantonazzo** [comment]
Sounds good to me!
